#!/bin/bash
sg docker "docker info &>/dev/null"
if [[ $? -eq 1 ]]
then
    echo "Docker connect error!"
    exit
fi

xhost + local: &>/dev/null

sg docker "docker run -dit --rm \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/.config:/root/.config \
    -v $HOME/.cache:/root/.cache \
    -v $HOME/Music:/root/Music \
    -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
    -v /usr/share/icons:/usr/share/icons:ro \
    -e DISPLAY \
    -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
    --device /dev/snd \
    --device /dev/dri \
    --ipc host \
qzwlecr/netease-cloud-music-docker-version &>/dev/null"
